// Code generated by mockery v2.21.4. DO NOT EDIT.

package notify

import mock "github.com/stretchr/testify/mock"

// MockNotifier is an autogenerated mock type for the Notifier type
type MockNotifier struct {
	mock.Mock
}

// Send provides a mock function with given fields: value
func (_m *MockNotifier) Send(value Notification) error {
	ret := _m.Called(value)

	var r0 error
	if rf, ok := ret.Get(0).(func(Notification) error); ok {
		r0 = rf(value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockNotifier interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockNotifier creates a new instance of MockNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockNotifier(t mockConstructorTestingTNewMockNotifier) *MockNotifier {
	mock := &MockNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
