name: validate_commit
on: [ push ]
jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Check golang format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start container with test databases
        run: docker-compose -f test/docker-compose.yml up -d
      - name: Prepare sqlite database
        run: make prepare-sqlite
      - name: Wait for docker containers to start
        run: sleep 30
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Install tparse for pretty test results
        run: go install github.com/mfridman/tparse@latest
      - name: Run test
        run: make test-all
